name: CI/CD

on:
  push:
    branches: [ "cicd" ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: EC2에 접속
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secret.HOST }}
          username: ${{ secret.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
        script: |
          echo "----------"
          cd /home/ubuntu/sikhoo0-server
          ls
          git pull
          yarn build
          pm2 list
          pm2 kill
          pm2 list
          yarn start:prod
          pm2 list
